import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import "../src/styles/globals.css";
import { ReactNode } from "react";
import Navbar from "@/src/components/Navbar/Navbar";
import { Provider } from "../context/index";
interface IProps {
  children: ReactNode;
}
export const metadata = {
  title: "desi buck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${inter.className} bg-[#efeeee]`}>
          <Navbar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
